from pathlib import Path

PAGE = Path("index.html")
text = PAGE.read_text(encoding="utf-8")

replacements = {
    '<title>Neurosymbolic Decision Machines | NSDM Institute</title>': '<title>Governed AI for Decisions, Actions and Infrastructure | NSDM Institute</title>',
    '<meta name="description" content="NSDM stands for Neurosymbolic Decision Machines: systems that perceive, generate, recommend, simulate and act while checking what their evidence, model of the world, authority and consequences actually justify.">': '<meta name="description" content="MetaForgeX builds provider-neutral intelligence that determines whether an AI workload, decision or action is supported, authorised, compliant and worth its cost before execution and throughout runtime.">',
    '<meta property="og:title" content="Neurosymbolic Decision Machines | NSDM Institute">': '<meta property="og:title" content="Governed AI for Decisions, Actions and Infrastructure | NSDM Institute">',
    '<meta property="og:description" content="NSDM stands for Neurosymbolic Decision Machines: systems that perceive, generate, recommend, simulate and act while checking what their evidence, model of the world, authority and consequences actually justify.">': '<meta property="og:description" content="Provider-neutral intelligence for evidence-bound decisions, authorised actions, sovereign workload routing and governed AI outcome economics.">',
    '<meta name="twitter:title" content="Neurosymbolic Decision Machines | NSDM Institute">': '<meta name="twitter:title" content="Governed AI for Decisions, Actions and Infrastructure | NSDM Institute">',
    '<meta name="twitter:description" content="NSDM stands for Neurosymbolic Decision Machines: systems that perceive, generate, recommend, simulate and act while checking what their evidence, model of the world, authority and consequences actually justify.">': '<meta name="twitter:description" content="Provider-neutral intelligence for evidence-bound decisions, authorised actions, sovereign workload routing and governed AI outcome economics.">',
    '"name": "Neurosymbolic Decision Machines | NSDM Institute",': '"name": "Governed AI for Decisions, Actions and Infrastructure | NSDM Institute",',
    '"description": "NSDM stands for Neurosymbolic Decision Machines: systems that perceive, generate, recommend, simulate and act while checking what their evidence, model of the world, authority and consequences actually justify.",': '"description": "MetaForgeX builds provider-neutral intelligence that determines whether an AI workload, decision or action is supported, authorised, compliant and worth its cost before execution and throughout runtime.",',
    '"dateModified": "2026-07-29",': '"dateModified": "2026-08-04",',
    '<div class="eyebrow">Neurosymbolic Decision Machines · Independent research programme</div>': '<div class="eyebrow">MetaForgeX AI · NSDM Institute · Independent research programme</div>',
    '<h1>Can a system perceive, generate, recommend, simulate and act while knowing what its evidence, model of the world, authority and consequences actually <em>justify?</em></h1>': '<h1>Governed AI for decisions, actions and <em>infrastructure.</em></h1>',
    '<p class="lead"><strong>NSDM stands for Neurosymbolic Decision Machines.</strong> We are building AI systems that combine learned pattern recognition with explicit rules, evidence checks, world models, permissions and consequence-aware decisions.</p>': '<p class="lead"><strong>MetaForgeX builds provider-neutral intelligence</strong> that determines whether an AI workload, decision or action is supported, authorised, compliant and worth its cost—before execution and throughout runtime.</p>',
    '<p class="lead">In plain English: an AI may be able to see something, create something, suggest something or take an action. NSDM asks whether it has enough trustworthy evidence, understands the situation well enough, has permission to act, and knows what could happen if it is wrong.</p>': '<p class="lead">From evidence-bound decision systems to sovereign workload routing and outcome economics, we make AI operationally defensible. Capability is not permission, and low cost is not value unless the result is correct, accepted and authorised.</p>',
    '<a class="button" href="/research.html">Read the research</a>': '<a class="button" href="/research.html">Explore the research</a>',
    '<a class="button secondary" href="/papers.html">View papers</a>': '<a class="button secondary" href="#contact">Discuss a deployment</a>',
    '<figcaption>The model may be able to answer, recommend or act, but is it justified in doing so?</figcaption>': '<figcaption>The model may be capable of answering, recommending or acting. NSDM determines whether it is justified and permitted to do so.</figcaption>',
    '<h2>What NSDM actually does</h2>': '<h2>The control layer AI infrastructure is missing</h2>',
    '<p class="section-lead">Most AI evaluation asks whether a model is accurate, fluent, creative or useful. NSDM asks what must be true before its answer, recommendation, simulation or action should influence a person, product, customer, company or regulated decision.</p>': '<p class="section-lead">Cloud providers expose compute. Models produce outputs. Cost platforms report spend. MetaForgeX connects the unresolved questions: which evidence supports the decision, whether the actor has authority, where a workload may run, which route is justified, whether the outcome was accepted, and whether the full action can be audited.</p>',
    '<article class="card boundary-card"><div class="tag">Boundary 01</div><h3>Evidence-state</h3><p>Does the evidence support the claim, contradict it, fail to support it, or leave a necessary premise missing?</p></article>': '<article class="card boundary-card"><div class="tag">NSDM</div><h3>Evidence-bound decisions</h3><p>Determine whether a claim is supportable, whether a decision remains justified and whether an action is permitted under evidence, uncertainty, authority, policy and consequence.</p></article>',
    '<article class="card boundary-card"><div class="tag">Boundary 02</div><h3>Governance-state</h3><p>Is the action allowed, forbidden, ambiguous, outside authority, audit-sensitive, or requiring human review?</p></article>': '<article class="card boundary-card"><div class="tag">AI Efficiency OS</div><h3>Governed outcome economics</h3><p>Know what every AI task costs—and whether that expenditure produced a correct, authorised, accepted and deployable outcome.</p></article>',
    '<article class="card boundary-card"><div class="tag">Boundary 03</div><h3>Action-state</h3><p>Should the system answer, ask for clarification, request more evidence, abstain, refuse, escalate, or block?</p></article>': '<article class="card boundary-card"><div class="tag">Sovereign AI</div><h3>Federated workload intelligence</h3><p>Determine where a workload may legally run, which provider can execute it, which model and hardware route is justified, and how the allocation is audited.</p></article>',
    '<h2>Pattern recognition meets explicit reasoning.</h2>': '<h2>Capability becomes governed execution.</h2>',
    '<p>NSDM turns that combination into a decision machine: it checks whether the evidence is sufficient, whether its picture of the world is reliable, whether authority is clear, what the consequence of being wrong would be, and what the system should do next.</p>': '<p>NSDM turns that combination into a decision machine: it checks whether evidence is sufficient, whether the world model is reliable, whether authority and jurisdiction are clear, what the consequence of error would be, and whether the system should answer, act, abstain, reroute or escalate.</p>',
    '<h2>Research architecture</h2>': '<h2>Research becomes governed infrastructure</h2>',
    '<p class="section-lead">NSDM links formal research, benchmark datasets, model experiments, verification tools, vertical applications, and enterprise governance.</p>': '<p class="section-lead">NSDM links formal research, benchmark datasets, model experiments and verification tools to runtime authorisation, sovereign workload placement and outcome-economics controls.</p>',
    '<article class="card"><span class="paper-status">Research track</span><h3>Sovereign Stack Boundaries</h3><p>Vendor dependence, local control, data exposure, authority, and human override.</p><div class="paper-meta"><a href="/papers.html#paper-6">View paper programme →</a></div></article>': '<article class="card"><span class="paper-status">Research track</span><h3>Sovereign Workload Boundaries</h3><p>Jurisdiction, data residency, provider capability, model placement, energy, cost, authority and human override.</p><div class="paper-meta"><a href="/papers.html#paper-6">View paper programme →</a></div></article>',
    '<div class="note"><strong>Research status — 28 July 2026:</strong> NSDM is being built in public. Current benchmarks are research instruments, not production certification or proof that every neurosymbolic architecture is safe, interpretable or correct. Null findings, narrowed claims and unresolved questions are preserved.</div>': '<div class="note"><strong>Research status — 4 August 2026:</strong> EXP-001 completed 40 sealed dual-human adjudications with 80% exact agreement, 85% exact-or-adjacent agreement and zero forbidden-inference violations. The experiment did not pass its Cohen’s kappa scale-up gate and isolated a procedural-claim boundary now being corrected in rubric v1.1. Null findings, narrowed claims and unresolved questions are preserved.</div>',
    '<h2>Independent research for better AI decisions.</h2>': '<h2>Build AI that can justify where, why and at what cost it acts.</h2>',
    '<p class="section-lead">MetaForgeX AI conducts independent research into justified AI, Neurosymbolic Decision Machines, governance, model evaluation, behavioural intelligence, and enterprise deployment.</p>': '<p class="section-lead">MetaForgeX AI develops the governance and economics control layer between AI intent and permitted execution: evidence-bound decisions, authorised actions, sovereign workload routing and cost-to-successful-outcome intelligence.</p>',
    '<p>NSDM Institute for Neurosymbolic Decision Machines · Research site updated 28 July 2026. AI should not only act. It should know whether it is justified.</p>': '<p>NSDM Institute for Neurosymbolic Decision Machines · Research site updated 4 August 2026. AI should not only act. It should know whether it is justified, authorised and worth its cost.</p>',
}

missing = []
for old, new in replacements.items():
    if old not in text:
        missing.append(old)
    text = text.replace(old, new)

if missing:
    raise SystemExit("Expected content not found:\n" + "\n---\n".join(missing))

PAGE.write_text(text, encoding="utf-8")
print(f"Updated {PAGE} with {len(replacements)} controlled content replacements.")
